### ISSUE TITLE
연봉 길게 입력했을 때 에러 발생

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#10]
연봉 관련해서 범위를 입력하면 아래와 같이 문제 발생

![image](https://user-images.githubusercontent.com/28730180/39405325-800d4bea-4bde-11e8-9496-20d8fda166a2.png)

![image](https://user-images.githubusercontent.com/28730180/39405320-5dc6fe5a-4bde-11e8-9256-2852a3a6b9ac.png)

**Comment by realdew** [comment]
DB의 연봉 TEXT 컬럼 사이즈를 변경하여 해결

JOB_AD 테이블 : SALARY_TEXT varchar 50
USER_RESUME 테이블 : SALARY_WANTED_TEXT varchar 50
