### ISSUE TITLE
h02@a 병원에서 s02@a 에게 면접 제안했는데

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#13]
s02@a 에서 요청을 확인할 수 없음

추가로

면접제안이 아니라 지원 요청(제안) 으로 변경

**Comment by realdew** [comment]
면접제안한 공고가 아직 공고 시작일자가 아님(5월 1일). 따라서 화면에 표시되지 않는 것이 정상.

다만, 병원에서 면접제안할 때, 아직 공고시작일이 도래하지 않는 공고는 선택이 불가능하도록 수정하여야 할 것임(단 UX 문제는 있을 수 있음)

**Comment by mangoos** [comment]
공고 시작일이 미래인 채용공고가 면접 제안을 할 수 있는 지 정책 결정 필요
[sun]check, to close list 에 등록
