### ISSUE TITLE
~~~panel.html 에서 로그아웃 이후  개인정보 잔여 이슈 및 리다이렉트 처리

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#14]
liveboard.html (메인으로) 리다이렉트 필요
지금은 로그아웃한 페이지에서 로그아웃되었습니다 메시지만 뜨고 그대로 멈춰있음

그리고 개인 정보가 그대로 남아있음.(캡쳐 참고)

![image](https://user-images.githubusercontent.com/28730180/39466332-535acb8c-4d63-11e8-9d0d-ee2bb325866a.png)

![image](https://user-images.githubusercontent.com/28730180/39466304-30beadb4-4d63-11e8-8ad3-bfc973b5d882.png)

**Comment by realdew** [comment]
처리 완료

p.s. 앞으로는 로그아웃시에 통신 장애 나지 않을 듯함
