### ISSUE TITLE
jobad -- D-day 오류

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#19]
오늘 마감인데 종료로 나옴
+1 해주어야 할 듯~~~

![image](https://user-images.githubusercontent.com/28730180/39468385-b18f4692-4d6d-11e8-84c0-9f77bbffbaa8.png)

![image](https://user-images.githubusercontent.com/28730180/39468395-bc7ee2c4-4d6d-11e8-8c32-065f13ed182e.png)

**Comment by realdew** [comment]
수정 완료
