### ISSUE TITLE
dentist_panel.html 에 이메일 아이디가 아닌 대표 이메일이 노출

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#22]
![image](https://user-images.githubusercontent.com/28730180/39469338-b186e70e-4d72-11e8-82c1-f5c3981adf3c.png)

![image](https://user-images.githubusercontent.com/28730180/39469377-d9771982-4d72-11e8-823a-a6bf234ec642.png)

![image](https://user-images.githubusercontent.com/28730180/39469392-eaf34550-4d72-11e8-834b-84f65fb9556e.png)

Email-id 와
대표 이메일 구분 필요해보임(순간적으로라도 헷갈리지 않게)

## 아래는 개인 유져 참고

![image](https://user-images.githubusercontent.com/28730180/39469456-43bce286-4d73-11e8-9026-b88c030812dd.png)
![image](https://user-images.githubusercontent.com/28730180/39469464-52a1ca3c-4d73-11e8-84b1-8aa5b10da57e.png)
![image](https://user-images.githubusercontent.com/28730180/39469478-63a0d742-4d73-11e8-95c6-eab715c65ee6.png)

**Comment by realdew** [comment]
수정완료
