### ISSUE TITLE
개인회원 이력서 등록 시 에러

### ISSUE THREAD

**Issue by mangoos** [realdew/dentiq-web#6]
개인 회원 register_resume.html 에서 
등록시 에러 발생

Column 'OPEN_YN' cannot be null~~~~ 

![image](https://user-images.githubusercontent.com/28730180/39405032-29f0a514-4bd8-11e8-8a03-0199307cae12.png)

**Comment by realdew** [comment]
수정 완료
register_resume.html에서 이력서 공개 여부는 '예/아니오' 이므로 반드시 하나는 선택하여야 함.
기존에는 '선택/예/아니오' 3개여서 이를 '예/아니오' 중에서 하나를 선택하도록 수정함
